import{createClient}from'https://esm.sh/@supabase/supabase-js@2.57.4';
const cfg=window.THT_CONFIG,db=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let S={characters:[],characterId:null,hunts:[],sessions:[]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const nf=n=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:1}).format(Number(n||0));
const short=n=>{n=Number(n||0);return Math.abs(n)>=1e6?nf(n/1e6)+'M':Math.abs(n)>=1e3?nf(n/1e3)+'k':nf(n)};
const dur=s=>{s=Number(s||0);return Math.floor(s/3600)+'h'+String(Math.floor((s%3600)/60)).padStart(2,'0')+'m'};
const date=d=>{if(!d)return'';const[y,m,x]=d.split('-');return x+'/'+m+'/'+y};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const sprite=n=>'https://www.tibiawiki.com.br/wiki/Special:Redirect/file/'+encodeURIComponent(String(n||'').trim().replace(/\s+/g,'_').replace(/(^|_)([a-z])/g,(_,a,b)=>a+b.toUpperCase())+'.gif');

function signed(on){$('#login').classList.toggle('hidden',on);$('#app').classList.toggle('hidden',!on);$('#tabs').classList.toggle('hidden',!on)}
async function boot(){const{data:{session}}=await db.auth.getSession();if(!session)return signed(false);signed(true);await loadCharacters()}
async function loadCharacters(){const{data,error}=await db.from('characters').select('id,name,created_at').order('created_at');if(error)throw error;S.characters=data||[];$('#character').innerHTML=S.characters.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');S.characterId=localStorage.getItem('tht.mobile.character')||S.characters[0]?.id||null;if(S.characterId&&!S.characters.some(x=>x.id===S.characterId))S.characterId=S.characters[0]?.id||null;if(S.characterId)$('#character').value=S.characterId;await loadData()}
async function loadData(){if(!S.characterId){S.hunts=[];S.sessions=[];render();return}$('#syncStatus').textContent='Atualizando...';const[h,s]=await Promise.all([db.from('hunts').select('*').eq('character_id',S.characterId).order('name'),db.from('sessions').select('*').eq('character_id',S.characterId).order('hunt_date',{ascending:false}).order('start_time',{ascending:false}).limit(250)]);if(h.error)throw h.error;if(s.error)throw s.error;S.hunts=h.data||[];S.sessions=s.data||[];localStorage.setItem('tht.mobile.character',S.characterId);render();$('#syncStatus').textContent='Atualizado agora';$('#syncStatus').className='status ok'}
function stat(name){const a=S.sessions.filter(x=>String(x.hunt_name).toLowerCase()===String(name).toLowerCase()),sec=a.reduce((v,x)=>v+Number(x.duration_seconds||0),0),hr=sec/3600,sum=k=>a.reduce((v,x)=>v+Number(x[k]||0),0),d=a.filter(x=>Number(x.damage)>0&&Number(x.duration_seconds)>0),ds=d.reduce((v,x)=>v+Number(x.duration_seconds),0),dv=d.reduce((v,x)=>v+Number(x.damage),0);return{n:a.length,sec,raw:hr?sum('raw_xp')/hr:0,xp:hr?sum('xp')/hr:0,bal:hr?sum('balance')/hr:0,dmg:ds?dv*3600/ds:0}}
function render(){renderHome();renderHunts();renderSessions()}
function renderHome(){const sec=S.sessions.reduce((v,x)=>v+Number(x.duration_seconds||0),0),hr=sec/3600,sum=k=>S.sessions.reduce((v,x)=>v+Number(x[k]||0),0),k=[['Tempo',dur(sec)],['Raw XP/h',short(hr?sum('raw_xp')/hr:0)],['Profit/h',short(hr?sum('balance')/hr:0)],['Sessões',nf(S.sessions.length)]];$('#kpis').innerHTML=k.map(([a,b])=>`<div class="kpi"><span>${a}</span><b>${b}</b></div>`).join('');const rows=S.hunts.map(h=>({...h,st:stat(h.name)})).filter(x=>x.st.n).sort((a,b)=>b.st.raw-a.st.raw).slice(0,5);$('#topHunts').innerHTML=rows.length?rows.map(x=>`<div class="session"><div class="head"><div><div class="title">${esc(x.name)}</div><div class="meta">${x.st.n} sessões • ${dur(x.st.sec)}</div></div><div class="score">${short(x.st.raw)}/h</div></div></div>`).join(''):'<div class="empty">Sem hunts registradas.</div>'}
function renderHunts(){$('#hunts').innerHTML=S.hunts.length?S.hunts.map(h=>{const s=stat(h.name);return`<div class="card hunt"><img src="${esc(h.image_path||'')}" onerror="this.style.visibility='hidden'"><div class="grow"><div class="title">${esc(h.name)}</div><div class="meta">${s.n} sessões • ${dur(s.sec)}</div><div class="metrics"><div class="mini"><span>Raw/h</span><b>${short(s.raw)}</b></div><div class="mini"><span>Profit/h</span><b>${short(s.bal)}</b></div><div class="mini"><span>Dano/h</span><b>${s.dmg?short(s.dmg):'—'}</b></div></div></div></div>`}).join(''):'<div class="empty">Nenhuma hunt cadastrada.</div>'}
function renderSessions(){$('#sessions').innerHTML=S.sessions.length?S.sessions.map(s=>`<button class="session" data-id="${s.id}"><div class="head"><div><div class="title">${esc(s.hunt_name)}</div><div class="meta">${date(s.hunt_date)} • ${esc(String(s.start_time||'').slice(0,5))} • ${dur(s.duration_seconds)}</div></div><span class="pill">${nf(s.monsters)} mobs</span></div><div class="metrics"><div class="mini"><span>Raw/h</span><b>${short(s.raw_xph)}</b></div><div class="mini"><span>Profit</span><b>${short(s.balance)}</b></div><div class="mini"><span>Dano/h</span><b>${Number(s.damageph)>0?short(s.damageph):'—'}</b></div></div></button>`).join(''):'<div class="empty">Nenhuma sessão encontrada.</div>';$$('[data-id]').forEach(b=>b.onclick=()=>details(b.dataset.id))}
function details(id){const s=S.sessions.find(x=>String(x.id)===String(id));if(!s)return;$('#sheetTitle').textContent=s.hunt_name+' • '+date(s.hunt_date);const mobs=Array.isArray(s.monster_details)?[...s.monster_details]:[],total=mobs.reduce((v,x)=>v+Number(x.count||0),0)||Number(s.monsters||0)||1;const metrics=`<div class="grid"><div class="kpi"><span>Raw XP/h</span><b>${short(s.raw_xph)}</b></div><div class="kpi"><span>XP/h</span><b>${short(s.xph)}</b></div><div class="kpi"><span>Profit</span><b>${short(s.balance)}</b></div><div class="kpi"><span>Mobs</span><b>${nf(s.monsters)}</b></div></div>`;const comp=mobs.length?'<div class="card"><h2>Composição</h2>'+mobs.sort((a,b)=>b.count-a.count).map(m=>`<div class="mob"><img src="${sprite(m.name)}" onerror="this.style.visibility='hidden'"><div><div class="title">${esc(m.name)}</div><div class="meta">${nf(m.count)} kills</div></div><div class="pct">${nf(100*Number(m.count||0)/total)}%</div></div>`).join('')+'</div>':'<div class="card"><div class="meta">Esta sessão não possui detalhamento histórico por espécie.</div></div>';$('#sheetBody').innerHTML=metrics+comp;$('#sheet').classList.remove('hidden')}

$('#loginBtn').onclick=async()=>{const b=$('#loginBtn');b.disabled=true;$('#loginStatus').textContent='Entrando...';try{const{error}=await db.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error)throw error;$('#password').value='';$('#loginStatus').textContent='';await boot()}catch(e){$('#loginStatus').textContent=e.message;$('#loginStatus').className='status error'}finally{b.disabled=false}};
$('#logout').onclick=async()=>{await db.auth.signOut();S={characters:[],characterId:null,hunts:[],sessions:[]};signed(false)};
$('#character').onchange=async e=>{S.characterId=e.target.value;await loadData()};
$('#refresh').onclick=()=>loadData().catch(e=>{$('#syncStatus').textContent=e.message;$('#syncStatus').className='status error'});
$('#closeSheet').onclick=()=>$('#sheet').classList.add('hidden');$('#sheet').onclick=e=>{if(e.target===$('#sheet'))$('#sheet').classList.add('hidden')};
$$('#tabs button').forEach(t=>t.onclick=()=>{$$('#tabs button').forEach(x=>x.classList.remove('active'));t.classList.add('active');['home','hunts','sessions','more'].forEach(p=>$('#p-'+p).classList.toggle('hidden',p!==t.dataset.page));scrollTo({top:0,behavior:'smooth'})});
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
db.auth.onAuthStateChange((_e,session)=>{if(!session)signed(false)});
boot().catch(e=>{signed(false);$('#loginStatus').textContent=e.message;$('#loginStatus').className='status error'});